version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: marketscan360-postgres
    environment:
      POSTGRES_DB: marketscan360
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "5688353"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
